name: flutter_adb
description: "Native dart implementation of a network ADB (Android Debug Bridge) client."
version: 0.1.1
repository: https://github.com/Jellepepe/flutter_adb

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  pointycastle: ^3.9.1

dev_dependencies:
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
